# Generated by Django 4.1.2 on 2022-10-06 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.IntegerField(verbose_name='Количество ядер')),
                ('ram', models.IntegerField(verbose_name='Объем RAM')),
                ('hdd', models.IntegerField(verbose_name='Объем HDD')),
                ('status', models.CharField(choices=[('started', 'started'), ('blocked', 'blocked'), ('stopped', 'stopped')], default='started', max_length=7, verbose_name='Статус сервера')),
            ],
        ),
    ]
